# Generated by Django 5.2 on 2025-04-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('assunto', models.TextField(max_length=300)),
                ('mensagem', models.TextField(max_length=300)),
            ],
        ),
    ]
